version: "3.0"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.web
    ports:
      - "7979:80"
    volumes:
      - ./jobs:/var/www/html/jobs
      - ./files:/var/www/html/files
    environment:
      PHP_INI_POST_MAX_SIZE: 120M
      PHP_INI_UPLOAD_MAX_FILESIZE: 120M
  worker:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.worker
    volumes:
      - ./jobs:/usr/src/app/jobs
      - ./files:/usr/src/app/files
      - /var/run/docker.sock:/var/run/docker.sock
